### ISSUE TITLE
addPrimaryKey missing opt_autoInc  in lovefield.d.ts

### ISSUE THREAD

**Issue by codeBelt** [google/lovefield#108]
Currently it is:
`addPrimaryKey(columns: Array<string>|Array<IndexedColumn>): TableBuilder`

Should be this:
`addPrimaryKey(columns: Array<string>|Array<IndexedColumn>, opt_autoInc?: boolean): TableBuilder`

https://github.com/google/lovefield/blob/master/dist/lovefield.d.ts#L217

**Comment by freshp86** [comment]
FYI, updated local copy of Typescript definitions. Still need to send a pull request for updating https://github.com/borisyankov/DefinitelyTyped/tree/master/lovefield.

**Comment by freshp86** [comment]
FYI,waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6599 before closing this issue.
