### ISSUE TITLE
Selecting random record

### ISSUE THREAD

**Issue by akhil110** [google/lovefield#109]
How I can select one random record from a table. I don't find and random() method in the API.

**Comment by freshp86** [comment]
There is no built-in functionality to select a random record. There might be ways to get around this if you know the number of rows. For example

var random = ....something between 0 and N-1, where N the number of rows.
`db.select().from(table).skip(random).limit(1).exec();`

Also questions like this belong to our discussion forum, not in the bug tracker. Please continue this discussion there if you have additional questions.
