### ISSUE TITLE
addNullable should accept Array<string> not Array<Column> in lovefield.d.ts

### ISSUE THREAD

**Issue by codeBelt** [google/lovefield#110]
Seems like the expected usage is:
`addNullable(['groupId']);`

If that is true the method should accept `Array<string>` not `Array<Column>`.

`addNullable(columns: Array<string>): TableBuilder`

**Comment by freshp86** [comment]
Thanks for reporting this. Indeed this should be array of string, see https://github.com/google/lovefield/blob/master/lib/schema/table_builder.js#L407. Will fix soon.
