### ISSUE TITLE
Lovefield not working on Safari

### ISSUE THREAD

**Issue by codeBelt** [google/lovefield#111]
Lovefield not working on Safari. I am using the same code as the Quick Start

I am changing the store type to:
`var storeType = lf.schema.DataStoreType.WEB_SQL;`

Using Safari Version 9.0.1 (11601.2.7.2). If you open the console you will see:

`SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.`

Website: http://codebelt.github.io/lovefield/
Repo: https://github.com/codeBelt/lovefield

Side note: on Cordova app iOS 9 you will see `[object SQLError]`

**Comment by freshp86** [comment]
I just tried http://codebelt.github.io/lovefield/ on the exact same version on Safari and can't reproduce. I see the expected outut "Get a cup of coffee ...."

**Comment by codeBelt** [comment]
I can get it to happen by clearing the cache: Safari > Preferences > Privacy > Remove All Website Data... and refreshing the page.

If you restart Safari the error does not appear until you clear the cache again.

**Comment by freshp86** [comment]
Ok, I was able to reproduce it following these steps. Note that if you open a new tab instead of refreshing the existing one, then it works fine. It seems to me that this is a Safari bug (something is not correctly cleaned up for the tabs that are open when "Remove All Website Data" is called). My guess is that this can be reproduced with any page that uses WebSQL and not just Lovefield.

**Comment by codeBelt** [comment]
Ok, I was able to figure out my issue with Safari issue and Cordova. I thought it was the above thing but I was wrong.

I get a `[object SQLError]` error if I create a table with the name 'Group'. Renaming it fixes the issues.
Check it out: 

Website: http://codebelt.github.io/lovefield/
Repo: https://github.com/codeBelt/lovefield

```
schemaBuilder.createTable('Group').
                    addColumn('id',                         lf.Type.INTEGER).
                    addColumn('qty',                        lf.Type.INTEGER).
                    addColumn('fk_productId',               lf.Type.INTEGER).
                    addPrimaryKey(['id'], true);
```

**Comment by freshp86** [comment]
I am able to reproduce the issue with WebSQL and a table named "Group" on Chrome too, so this is not Safari specific. Filed https://github.com/google/lovefield/issues/112 to track this separately.
