### ISSUE TITLE
Uncaught #<Event> on running schemaBuilder.connect() ?

### ISSUE THREAD

**Issue by martiansideofthemoon** [google/lovefield#113]
@arthurhsu , I was using lovefield for a project of mine. It was working perfectly a couple of days ago. However, on running the same code today, I got the following error on (anonymous function)	@	lovefield.js:2092. What could be a reason? I'm using Google Chrome. I tested it on the Quick Start code as well (the only change being replacing the script src to :- 
`    <script src="lf_scripts/lovefield.js"></script>`
where lf_scripts is a local folder containing the lovefield.js file. What could be a plausible reason for the same?

**Comment by arthurhsu** [comment]
I just tested the quick start example and found no issues. If you had modified any of the examples, please give your source code and someone may be able to provide a more useful help than this reply.

Questions like this belong to our discussion forum, not in the bug tracker. Please continue this discussion there if you have additional questions.

**Comment by martiansideofthemoon** [comment]
@arthurhsu , I'm sorry for posting this here, I've moved it to https://groups.google.com/forum/#!topic/lovefield-users/a9qampu2dT4
