### ISSUE TITLE
Field names in "splice" change objects in observable queries

### ISSUE THREAD

**Issue by mgd134** [google/lovefield#115]
Hi. I'm using lovefield in a project that uses the [Aurelia framework](http://aurelia.io/). We use jspm for package management. We make extensive use of observable queries to update our UI. After a recent `jspm update` I noticed that the fields in `splice`-type changes changed names. As per the lovefield docs, I had been expecting the changes to be delivered in the same manner as [Array.observe](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/observe), and they were until this recent `jspm update`. The fields `removed` and `addedCount` now seem to be reported as `Rg` and `Pg` respectively.

So to my questions: Is this an issue with lovefield? Could an update to another library be causing this issue? Or should I just use the new field names and it currently works as expected?

Thanks.

**Comment by freshp86** [comment]
This sounds like a bug, probably introduced by the latest version 2.1.2. The names should not have been changed. Will investigate. In the meantime can you stick with previous version to workaround this issue.

**Comment by mgd134** [comment]
Just was talking with a colleague and he had a good question: with the weird field names could this possibly have something to do with minification?

**Comment by freshp86** [comment]
Absolutely. Specifically the bug is at those lines, https://github.com/google/lovefield/blob/master/lib/diff_calculator.js#L170-L174. Putting quotes around the keys of that object fixes the problem. Working on adding some tests though along with the fix.

**Comment by mgd134** [comment]
Thanks!
