### ISSUE TITLE
MultiColumnOrPass optimization throws error if execution plan already optimized

### ISSUE THREAD

**Issue by simon-weber** [google/lovefield#118]
Here's the full traceback:
```
TypeError: Cannot read property 'table' of undefined at lf.proc.MultiColumnOrPass.replaceWithIndexRangeScan_
at lf.proc.MultiColumnOrPass.rewrite
at null.<anonymous>
at Array.forEach (native)
at lf.proc.PhysicalPlanRewriter.generate
at lf.proc.PhysicalPlanFactory.createPlan_
at lf.proc.PhysicalPlanFactory.create
at lf.proc.DefaultQueryEngine.getPlan
at lf.query.BaseBuilder.getPlan_
at lf.query.BaseBuilder.getTaskItem
```

I'm triggering it from [this code](https://github.com/simon-weber/Autoplaylists-for-Google-Music/blob/ea2b5d24443c188fd33f412575a5619526db52e9/src/js/trackcache.js#L75), but only when building a select containing the construct: `and(..., or(..., ...))`. Queries of the form `and(..., and(..., ...))` and `and(..., or(...))` both work as expected, so I think there's something happening in `MultiColumnOrPass`. All of my fields are indexed in a memory store.

That form of query alone isn't enough to reproduce -- I tried it with the todo example and it worked. I'll keep working on a self-contained test case, but I wanted to post early in case something about my client code jumped to you (eg I'm suspicious of the `apply` and `bind` [here](https://github.com/simon-weber/Autoplaylists-for-Google-Music/blob/ea2b5d24443c188fd33f412575a5619526db52e9/src/js/trackcache.js#L53)).

**Comment by simon-weber** [comment]
Ah, yes, it requires indexed columns to reproduce. Here's a patch to the demo app to reproduce it:
```diff
~/other/lovefield/demos/todo$ (*p*) git diff
diff --git a/demos/todo/todo.html b/demos/todo/todo.html
index 42b5fff..02e6d05 100644
--- a/demos/todo/todo.html
+++ b/demos/todo/todo.html
@@ -16,7 +16,9 @@ schemaBuilder.createTable('Item').
     addColumn('deadline', lf.Type.DATE_TIME).
     addColumn('done', lf.Type.BOOLEAN).
     addPrimaryKey(['id']).
-    addIndex('idxDeadline', ['deadline'], false, lf.Order.DESC);
+    addIndex('idxDeadline', ['deadline'], false, lf.Order.DESC).
+    addIndex('idxDescription', ['description'], false, lf.Order.DESC).
+    addIndex('idxDone', ['done'], false, lf.Order.DESC);

 var todoDb;
 var item;
@@ -32,7 +34,15 @@ schemaBuilder.connect().then(function(db) {

   return db.insertOrReplace().into(item).values([row]).exec();
 }).then(function() {
-  return todoDb.select().from(item).where(item.done.eq(false)).exec();
+  return todoDb.select().from(item).where(
+          lf.op.and(
+              item.done.eq(false),
+              lf.op.or(
+                  item.id.eq(2),
+                  item.description.eq('get a cup of coffee')
+                  )
+              )
+          ).exec();
 }).then(function(results) {
   results.forEach(function(row) {
     console.log(row['description'], 'before', row['deadline']);
```

**Comment by simon-weber** [comment]
Downgrading to 2.0.66 to prevents this.

**Comment by arthurhsu** [comment]
The actual bug is that connect did not throw an exception: boolean field is not indexable.

**Comment by simon-weber** [comment]
Ah, makes sense.

Is there a similar problem with [this call to connect](https://github.com/simon-weber/Autoplaylists-for-Google-Music/blob/5a834a7352045a7ad2f1e248d3d58ad1a19e76a4/src/js/trackcache.js#L8) (using  [these fields](https://github.com/simon-weber/Autoplaylists-for-Google-Music/blob/5a834a7352045a7ad2f1e248d3d58ad1a19e76a4/src/js/track.js#L26))? I don't have any boolean columns.

**Comment by arthurhsu** [comment]
boolean, arraybuffer, and object are not indexable. The rest should be fine. I don't see a similar problem in your code from a quick glance.

**Comment by simon-weber** [comment]
There seems to be something more to this than the schema.

Using this schema:
```diff
diff --git a/demos/todo/todo.html b/demos/todo/todo.html
index 42b5fff..207d1ab 100644
--- a/demos/todo/todo.html
+++ b/demos/todo/todo.html
@@ -16,7 +16,8 @@ schemaBuilder.createTable('Item').
     addColumn('deadline', lf.Type.DATE_TIME).
     addColumn('done', lf.Type.BOOLEAN).
     addPrimaryKey(['id']).
-    addIndex('idxDeadline', ['deadline'], false, lf.Order.DESC);
+    addIndex('idxDeadline', ['deadline'], false, lf.Order.DESC).
+    addIndex('idxDesc', ['description'], false, lf.Order.DESC);
```

This query crashes:
```diff
 }).then(function() {
-  return todoDb.select().from(item).where(item.done.eq(false)).exec();
+  return todoDb.select().from(item).where(
+          lf.op.and(
+              item.id.eq(1),
+              lf.op.or(
+                  item.id.eq(2),
+                  item.description.eq('Get a cup of coffee')
+                  )
+              )
+          )
+      .exec();
 }).then(function(results) {
   results.forEach(function(row) {
     console.log(row['description'], 'before', row['deadline']);
```

but removing the surrounding `and` prevents a crash:
```diff
 }).then(function() {
-  return todoDb.select().from(item).where(item.done.eq(false)).exec();
+  return todoDb.select().from(item).where(
+          lf.op.or(
+              item.id.eq(2),
+              item.description.eq('Get a cup of coffee')
+              )
+          )
+      .exec();
 }).then(function(results) {
```

**Comment by freshp86** [comment]
Thanks for the report. At first glance I can see that the bug seems to be at https://github.com/google/lovefield/blob/master/lib/proc/multi_column_or_pass.js#L162-L169, where the code assumes that a TableAccessFullStep must exist in the query execution plan by the time this optimization is applied, but it does not for the example query. Will investigate further for the proper fix.

**Comment by freshp86** [comment]
FYI, uploaded the fix and corresponding test at https://github.com/google/lovefield/commit/ef224971e0122e51302b9c41b9b860a477b21ee4. Will be merging it to master sometime tomorrow.

**Comment by freshp86** [comment]
@arthurhsu: Only ARRAY_BUFFER and OBJECT types are not indexable, see https://github.com/google/lovefield/blob/master/lib/schema/table_builder.js#L508. Booleans columns are allowed to be indexed (although it makes little sense). I am renaming this bug to reflect the real issue here.

**Comment by simon-weber** [comment]
Thanks!
