### ISSUE TITLE
Suggested process for testing database upgrades

### ISSUE THREAD

**Issue by sgerace** [google/lovefield#119]
Is there a suggested process for testing database upgrades to ensure that I've migrated all of my existing data appropriately? At the moment it is difficult to test because, in my development machine, once the upgrade is performed, the database version is incremented and my upgrade function never runs again. Even having a simple way to delete the database would be helpful. Ideally, it would be nice to have a way of testing the `onUpdate` function without actually applying the upgrade (so I could run the function multiple times). 

I guess I'm just looking for a little guidance since there have been several occasions now where I have missed something in the upgrade, inadvertantly gotten my database into an invalid state, and then had to resort to somewhat extreme measures (adding in a temporary call to `indexedDB.deleteDatabase("db")`) to cleanup my mess.

**Comment by freshp86** [comment]
Moved this discussion to the forum. Please follow up from https://groups.google.com/forum/#!topic/lovefield-users/YlppkpwaYlY.
