### ISSUE TITLE
Failed to add new table to old DB

### ISSUE THREAD

**Issue by unbug** [google/lovefield#133]
My old DB has three tables,and all of them has datas.
I want to add a new table to it,so I just do it like this.
```
schemaBuilder .createTable('newTable')
```
but it give's me error
```
Uncaught NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```
I have to create a new DB for the new table?

**Comment by freshp86** [comment]
Did you go through the DB schema upgrade process to modify the schema? See https://github.com/google/lovefield/blob/master/docs/spec/03_life_of_db.md#33-database-upgrade.

**Comment by unbug** [comment]
So,in my case,the idea is change the version?
```
lf.schema.create('Codelf', 1);
```
to
```
lf.schema.create('Codelf', 2);
```

**Comment by arthurhsu** [comment]
Please use user group for usage questions.
https://groups.google.com/forum/#!forum/lovefield-users
