### ISSUE TITLE
Lovefield DB Inspector does not show databases

### ISSUE THREAD

**Issue by kenjitayama** [google/lovefield#134]
Hi, I got excited finding this Chrome extension, but unfortunately it didn't work.
I opened my website using Lovefield and the Lovefield Inspector, but the database dropdown is empty.
I started debugging the extension (from Lovefield v2.1.5), and got `undefined` at the following window.alert.

**panel.js**
```
    chrome.devtools.inspectedWindow.eval(
        evalStatement,
        function(results, exception) {
          window.alert(results);
```

I ran `gulp zip` at `tools/devtools`, unzipped the created zipfile, and loaded to Chrome.

Chrome : 48.0.2564.82 (64-bit)
Mac OS : 10.11.3

**Comment by arthurhsu** [comment]
You did not specify enableInspector to true during your debugging, see 

https://github.com/google/lovefield/blob/master/tests/base/inspect_test.js#L97

for example. For security concerns, databases are not inspectable by default.

**Comment by kenjitayama** [comment]
@arthurhsu 
Thank for for the advice, I got a bit further.

Now I have  `Cannot inspect database on this page.`, and I got `'{}'` for `results` and `undefined` for `exception`.

I digged in a bit more and did the following in the console
```
lf.debug.listDb_() 
```
and got this.
```
“{“app”:2}”
```
'app' is actually my database name.

I couldn't figure out what `chrome.devtools.inspectedWindow` is and I'm stuck again…
Am I missing something else?

**Comment by freshp86** [comment]
Does your DB have any tables? The error is implying that no tables were found, see https://github.com/google/lovefield/blob/master/tools/devtools/panel.js#L65-L70. Also let's continue the discussion on the forum, it is more suited for such issues.

**Comment by kenjitayama** [comment]
Yes, my DB has tables.
Seeing the lines you pointed out, they look like checking DBs instead of tables.
I will try creating a live reproduction, and continue on the forum.
Thanks @arthurhsu and @freshp86 !

**Comment by kenjitayama** [comment]
I got it working and I'd like to conclude in this issue.
I was loading lovefield twice (one from bower and another from SPAC/Closure compiled source), and some how it was causing trouble. I removed the one from bower and now I am able to use the Inspector!
