### ISSUE TITLE
Update doesn't work when using lf.op.and in where filter

### ISSUE THREAD

**Issue by kheaactua** [google/lovefield#138]
Using version 2.1.6 (00b9acf) my update query works when I do:

```javascript
.where(event_table.id.eq(lf.bind(3))
```

but now
```javascript
.where(lf.op.and(event_table.id.eq(lf.bind(3)), site_table.id.eq(lf.bind(2))))
```

The code is the same in the examples in issue !136

The explainations I get for the latter are:

```javascript
console.log(query.explain(query.bind(vals)));
```
```
update(Event)
-select(combined_pred_and)
--table_access(Event)
```

```javascript
promises.push(query.bind(vals).exec().then(function() { console.debug(query.explain()); }));
```
```
48x update(Event)
-select(combined_pred_and)
--table_access(Event)
```

I've checked the values manually.  The result is that the two fields I'm trying to set (`avgHeight` and `avgScore`) are null.  As soon as `lf.op.and` is used the explanations don't really tell me anything.

But for instance, I print out the values before binding, I get:
```
[57.34657809779381, 0.8733333333333334, 15, 1048]
update(Event)
-select(combined_pred_and)
--table_access(Event)
```
and when I check my table, I have:
```json
value: {"id": 1048, "siteId": 15, "date": 1454759446959, "snapshot": "39.jpg", "avgHeight": null, "avgScore": null}
```
so I know the id values are right.

But yeah, when I drop the `lf.op.and` and use simply one key (which my schema supports anyways), it works perfectly,and the explanations are good.

(for simplicity, all the relevant code)
```javascript
// Update event hight/rating.  TODO define this more globally
var query = db.update(event_table)
	.set(event_table.avgHeight, lf.bind(0))
	.set(event_table.avgScore,  lf.bind(1))
	.where(lf.op.and(
		site_table.id.eq(lf.bind(2)),
		event_table.id.eq(lf.bind(3))
	))
	;

var promises = [];
updates.forEach(function(vals) {
	console.debug(vals);
	console.log(query.explain(query.bind(vals)));
	promises.push(query.bind(vals).exec().then(function() { console.debug(query.explain()); }));
});
return Promise.all(promises)
	.then(function() {
		console.debug('queries executed');
	});
})
```

Thanks

**Comment by freshp86** [comment]
Thanks for the report. Will try to reproduce and update this thread with findings.

**Comment by freshp86** [comment]
I am confused by your  example query
```
.where(lf.op.and(event_table.id.eq(lf.bind(3)), site_table.id.eq(lf.bind(2))))
```

are you using an UPDATE query that refers to two different tables, event_table and site_table? This is not allowed.

**Comment by kheaactua** [comment]
Ack!  I see the problem now.

The goal was
```sql
UPDATE table SET col=val WHERE event_id=x AND site_id=y
```

As soon as I read your comment, I saw my mistake.  The query should read
```javascript
.where(lf.op.and(event_table.id.eq(lf.bind(3)), event_table.siteId.eq(lf.bind(2))))
```

This is really obvious, I think I just got tunnel vision while trying to debug it.  Sorry about that.
