### ISSUE TITLE
testing with DataStoreType.Memory gives error code 352: "IndexedDB is not supported by platform."

### ISSUE THREAD

**Issue by bsr203** [google/lovefield#143]
I thought I may be able to test with in memory store type like 

```
schemaBuilder.connect({
        storeType: lf.schema.DataStoreType.Memory,
      }).then(database => {

```

but I get error

```
not ok 1 Error: http://sn.im/2a0j3wn?c=352
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { code: 352, message: 'http://sn.im/2a0j3wn?c=352' }
    at: Test.run (/Users/bsr/test/client/node_modules/blue-tape/blue-tape.js:26:12)
  ...
```

i am using `jsdom` for testing. Why is lovefield checking for `indexeddb` if I configured as `Memory`

**Comment by arthurhsu** [comment]
Because you have a typo and default IndexedDB is used.

lf.schema.DataStoreType.MEMORY is the right spelling.

**Comment by bsr203** [comment]
thanks. It indeed works with the correctly spelled type.
