### ISSUE TITLE
Add semicolon ; to end of dist files

### ISSUE THREAD

**Issue by codeBelt** [google/lovefield#144]
Can you add a semicolon to the end of the ```/dist``` files? 

The issues is when concatenating with other libraries via a Grunt or Gulp task you get a ```Uncaught TypeError:``` because the libraries have merged together. To fix this code/libraries should have a semicolon at the end as a separator.

Keep up the good work. I love Lovefield!

**Comment by arthurhsu** [comment]
We are unable to accommodate that request since most files are generated by Closure compiler automatically. If you have the need, please change your grunt/gulp script to do so.

**Comment by freshp86** [comment]
Re-opening this issue. The missing semicolon at the end is can actually be fixed. Will make sure this has been fixed in the next version.
