### ISSUE TITLE
Implement multi-column index

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#15]
Currently the cross-column indices are composed as strings, for example

id_name

this does not work well with numeric fields (e.g. integer, number, date) because of lexical sorting order e.g.

-1_1 > 10_1

need to change the design. Things to consider include (but not limited to)

B-tree with multilevel keys
Quad-tree
R*-tree
Grid File

**Comment by arthurhsu** [comment]
The multi-column index implementation is removed. Need to implement a working one. Most likely we would implement B-Tree with custom comparators as a stop-gap solution, but it cannot replace other possible data structures for different needs (e.g. spatial data with lots of range queries are more efficient with Grid File).

**Comment by freshp86** [comment]
Multi-column indices have now been implemented (using B-Tree). Marking this bug as fixed. We can open a separate bug when/if the time comes to add other implementations (Grid file etc).
