### ISSUE TITLE
Typescript type definition file contains errors

### ISSUE THREAD

**Issue by mattblang** [google/lovefield#152]
It looks like like the `type definition file` included in the `npm package` references `../es6-promise/es6-promise.d.ts`, which does not exist. This is causing multiple errors throughout the definition file.

**Comment by arthurhsu** [comment]
I'll let Demetrios to decide whether this is a bug or not. But if you use DefinitelyTyped, you need to configure your tsd.json like https://github.com/google/lovefield/blob/master/demos/todo_typescript/tsd.json.

I believe our design is to have you get the type definition files from DefinitelyTyped's repo, in that case this design makes much more sense.

**Comment by freshp86** [comment]
As Arthur said, the typescript definitions file is designed to be pulled from the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/cc3d223a946f661eff871787edeb0fcb8f0db156/lovefield) repository. For an example of how it is supposed to be used see [todo_typescript](https://github.com/google/lovefield/tree/master/demos/todo_typescript) demo (see tsd.json which pulls in the es6 dependency).

**Comment by mattblang** [comment]
@arthurhsu @freshp86 Thanks so much! What I am doing now (using `typings` since` tsd` was [deprecated](https://github.com/DefinitelyTyped/tsd/issues/269)) is issuing the command `typings install dt~lovefield --global --save`. I read on the [typings GitHub page](https://github.com/typings/typings#updating-from-0x-to-10) that as of `1.x` the repository has to be explicitly specified.

Also, on a side note, it looks like it works when I `import * as lf from 'lf'`!

**Comment by arthurhsu** [comment]
Closing the bug, filed https://github.com/google/lovefield/issues/156 for improvement on our demo.
