### ISSUE TITLE
Uncaught [object Event]  error in Chrome app

### ISSUE THREAD

**Issue by ashwinkm** [google/lovefield#160]
Some of my [Boomerang app](https://chrome.google.com/webstore/detail/boomerang-soap-rest-clien/eipdnjedkpcnlmmdfdkgfpljanehloah) users are getting **Uncaught [object Event]** error while creating a project in the app.
Error is throwing in lovefield.js library at the line number 10.

I was not able to reproduce this issue on my machine. 
I have updated the lovefield library to the latest version. But still some users are reporting the same issue.
![image](https://cloud.githubusercontent.com/assets/11582049/15654441/db1747d8-26b1-11e6-992f-fae6d1b0914d.png)
Can you please check and tell me what causing this error.
More details are on [Boomerang issue tracker](https://github.com/ashwinkm/Boomerang-app-support/issues/1).

Thank you.

**Comment by freshp86** [comment]
Looked a bit at the information in the Boomerang issue tracker. The error is thrown from https://github.com/google/lovefield/blob/master/dist/lovefield.js#L2179-2182, which is not very helpful, since it is still not clear where is the exception originating from.

Without a consistent reproduction case it is hard to pinpoint what is wrong. At the very least, you could point us to the Lovefield related code in your app to take a look and see if anything suspicious stands out.

**Comment by ashwinkm** [comment]
Hi, Please find the code below. I have also attached the data model.
```
var dm = new DataModel();
dm.init().then(function () {
....
});
...
addProject: function (name) {
        var row = dm.project.createRow({
            name,
            last_accessed: Date.now()
        });

        return dm.db.insert().into(dm.project).values([row]).exec();
    },
...
```
addProject is called when user creates a new project.
All boomerang codes are compiled using babel and webpack.

Please let me know if you need any more details.

[DataModel.js.txt](https://github.com/google/lovefield/files/296055/DataModel.js.txt)

**Comment by freshp86** [comment]
Looking at DataModel.js the schema seems fine, but the public `init()` method is not re-entrant. If called twice it could cause unexpected behavior. You can see an example of the `DbService` class at the [olympia DB demo](https://github.com/google/lovefield/blob/master/demos/olympia_db/angular/demo.js#L57-119) of how to make such a method re-entrant.

Your snippet for `addProject` above has a syntactic error, so I assume this is just from copying/pasting to github and not in the actual code. But more importantly, it does not seem to wait for the Lovefield to finish initialization, so `dm.db` could be null by the time `addProject` is called. My suggestion would be to eliminate this possibility as follows.
```
addProject: function (name) {
  // Ensure that db has been initialized.
  return dm.getDb().then(function(db) {
    var row = dm.project.createRow({
      name: name, last_accessed: Date.now()
    }); 

    // Stop exposing dm.db as a public member, instead always grab a reference
    // by calling a new re-entrant getDb() method first.
    return db.insert().into(dm.project).values([row]).exec();
  }); 
}    
```
Again, see the example linked above on how to provide an async getDb() method and stop exposing db as a public member variable, such that it can't be accessed when not initialized yet.

Unrelated to the exception you are seeing, you can eliminate the usage of `that = this`, and also remove the dummy Promise at the end of `_connect()` method, (see attachment).
[DataModel.js.txt](https://github.com/google/lovefield/files/296153/DataModel.js.txt)

**Comment by arthurhsu** [comment]
Seems to be another usage problem. Please use our public forum for usage questions, thanks!
https://groups.google.com/forum/#!forum/lovefield-users
