### ISSUE TITLE
nested where clause combining "and" and "or" querys

### ISSUE THREAD

**Issue by ZeroCool-85** [google/lovefield#161]
Hello,

is it possible to combine variable an "and" and "or" query like this:

```javascript
if (where['field'].constructor === Array) {
           searchItems.forEach((item) => {
            searchWordInColumns = [];
            where['field'].forEach((data:string) => {
              searchWordInColumns.push(tableItem[data].match(item));
            });
            searchParam.push(lf.op.or.apply(null, searchWordInColumns));
          });
          db.select().from(tableItem).where(lf.op.and.apply(null, searchParam)).exec()
            .then(observe.next.bind(observe))
            .catch((err) => console.log(err));
}
```
SQL-Query should look like this: .... 
```sql
WHERE (
((building.street LIKE 'word1') OR (building.id_number LIKE 'word1') OR 
(building.zipcode LIKE 'word1') OR (building.city LIKE 'word1')) 
AND 
((building.street LIKE 'word2') OR (building.id_number LIKE 'word2') OR 
(building.zipcode LIKE 'word2') OR (building.city LIKE 'word2'))
); 
```

and so on for more search words.

At the moment I'll get an "EXCEPTION: AssertionError: Assertion failed".

Thank you!

**Comment by ZeroCool-85** [comment]
Problem is solved:
I had a console.log('SQL-Query', db.select().from(tableItem).where(lf.op.and.apply(null, searchParam)).toSql()); between, that was the Problem. Maybe is it a bug, that I get an "AssertionError" when I call .exec() after .toSql()??

**Comment by arthurhsu** [comment]
Please use our public forum if you have usage questions. Issue trackers are for Lovefield developers to identify bugs and work items. Thanks!

https://groups.google.com/forum/#!forum/lovefield-users
