### ISSUE TITLE
(node:8808) fs: re-evaluating native module sources is not supported

### ISSUE THREAD

**Issue by peterennis** [google/lovefield#164]
lovefield quickstart, updated version dependency to latest 2.1.8
![capture3892](https://cloud.githubusercontent.com/assets/140737/16249435/9fa7423c-37ca-11e6-9ca7-61d904b3a4b2.png)

**Comment by arthurhsu** [comment]
This is a bug on glob's npm package, which refers to an old version of graceful-fs. There's nothing Lovefield can do with it since we don't own glob.
