### ISSUE TITLE
Would it be remotely possible to make changes to the dump that is synced with Firebase in a way that doesn't break Lovefield?

### ISSUE THREAD

**Issue by mattblang** [google/lovefield#165]
I am very interested in using this in an Electron app, with the Firebase option as the data store. I am curious if it would be at all possible to make changes to the Firebase data store, from say an Android or iOS device, in a way that wouldn't break Lovefield.

**Comment by arthurhsu** [comment]
Yes it's possible. For usage questions, please use our forum to discuss.

https://groups.google.com/forum/#!forum/lovefield-users
