### ISSUE TITLE
Safari detection

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#168]
https://groups.google.com/forum/#!topic/lovefield-users/qL4hhic8MfU

Closure Safari detection code is causing problem in our Capability management code. We'll need to either fix Closure or use goog.labs.userAgent.browser.isSafari() instead.

**Comment by bimusiek** [comment]
I have been testing lovefield for past 2 weeks and I see 2 issues:
1. When you turn on "mobile" view in Chrome dev tools, then database returns empty records if you didn't pass which storage you want to use.
2. If you don't pass that you want to use WebSql, then it does not work on Safari. It loads it first time and then when reloading it shows no records.

**Comment by freshp86** [comment]
The behavior you are describing is known, and a fix should be coming sometime soon. The problem is that MEMORY_DB is used erroneously in mobile safari, if a backing store is not explicitly specified. Until the fix is out, the workaround is to explicitly specify the desired backing store.
