### ISSUE TITLE
Insert working incorrectly when connecting to multiple databases

### ISSUE THREAD

**Issue by JasonZStanley** [google/lovefield#169]
I am not sure if this is a bug in lovefield or if I am missing something fairly trivial. This was happening in my Electron application and I have distilled it down into a html example which is attached. [demo.zip](https://github.com/google/lovefield/files/391955/demo.zip)

The code below is the gist of what I am trying to run. This works as you would expect.

```
var m = new testModel();
m.createCategory("1", function() {
	m.createCategory("2", function() {
		m.getCategories(function(m, r) {
			console.log(r);
		});
	})
})
```

When I run the code it will log that I have 2 records. When I run it again it will log I have 4 records, then 6 and so on. Works fine with correct incrementing index and 1,2,1,2,1,2 category names.

If I include the second model strange behaviour occurs. All the model is doing is creating a new database and initializing the connection.

```
var m = new testModel();
var m2 = new irrelevantModel();
m.createCategory("1", function() {
	m.createCategory("2", function() {
		m.getCategories(function(m, r) {
			console.log(r);
		});
	})
})
```

When I run the following code the first time it works. It inserts 2 records as expected. [1:"1",2:"2"]. This is [id:name] if that wasn't clear.
When I run the code the second time I have 2 records with values [3:"1",4:"2"]. 1 and 2 are missing.
When I run the code a third time I still have 2 records with new values [5:"1",6:"2"]. 3 and 4 are missing.

Other Notes:
If I insert 3 records it will replace the first 2 and insert the third correctly as expected.
If I insert a single record with a random value. This will always overwrite the first stored record. For example. If I have "1" and "2" stored then rerun it and try to store "shoe" I will be left with "shoe", "2".

I do not receive an error. The docs say I can have 1 connection open for each database and this is what I have here as far as I understand it. 

To stop the error from occurring I can comment out the createTable method in the irrelevantModel class. 

It should also be noted that in my app this isn't the exact problem. In my app this issue manifests when I have 1 database with a single table and a second database with two tables. To get it to work as expected I need to comment out one of the two tables. If I have two databases with a single table each the issue doesn't appear to manifest.

```
class testModel {

    constructor() {
        this.connection = null;
        this.createTable();
    }

    createCategory(categoryName, cb) {
        this.connection.then(function(db) {
            var categories = db.getSchema().table('test');
            var rows = [ 
                categories.createRow({
                    'name': categoryName
                })
            ];

            db.insertOrReplace().into(categories).values(rows).exec().then(function(results) {
                cb(false, results);
            });
        });
    }

    getCategories(cb) {
        this.connection.then(function(db) {
            return db.select()
                .from(db.getSchema().table('test'))
                .exec();
        }).then(function(results) {
            return cb(false, results);
        });
    }

    createTable() {
        // Create table.
        var schemaBuilder = lf.schema.create('test', 1);
        schemaBuilder.createTable('test')
            .addColumn('id', lf.Type.INTEGER)
            .addColumn('name', lf.Type.STRING)
            .addPrimaryKey(['id'], true);

        // Store the open connection.
        this.connection = schemaBuilder.connect();
    }

}
```

```
class irrelevantModel {

    constructor() {
        this.connection2 = null;
        this.createTable();
    }

    createTable() {
        // Create table.
        var schemaBuilder = lf.schema.create('someOtherDb', 1);
        schemaBuilder.createTable('transaction')
            .addColumn('id', lf.Type.INTEGER)
            .addColumn('name', lf.Type.STRING)
            .addPrimaryKey(['id'], true);

        // Store the open connection.
        var connect = schemaBuilder.connect();
    }

}
```

**Comment by freshp86** [comment]
I think what you are describing is a side-effect of the underlying bug https://github.com/google/lovefield/issues/170.

**Comment by freshp86** [comment]
I believe this is fixed now by https://github.com/google/lovefield/commit/981a2a78b0b319cb5d027b30aef05dc143935ad1. Please re-open if it still happens.
