### ISSUE TITLE
Custom backstores

### ISSUE THREAD

**Issue by ncortines** [google/lovefield#173]
I think it would be interesting to add support for _custom_ **backstores**

I couldn't find anything in the documentation regarding this, so I think it would interesting to define and/or document some kind of API to do so.

Thanks

Juan

**Comment by ncortines** [comment]
I just noticed this other issue #100 

It is related, but rather than adding built-in backstores into the core lib, I think it would make more sense to make some slight changes on the architecture so a custom backstore can be added or required as an external module.

Does make sense?

**Comment by arthurhsu** [comment]
It's very unlikely to do plug-in architecture for custom backstores (though looks attractive). The query engine and the backstore have to have some knowledge about each other. Moreover, the backstore and the engine will be loaded at the boot time together, and it makes very little sense to require one from the other.
