### ISSUE TITLE
SQLite as data store

### ISSUE THREAD

**Issue by hatemhosny** [google/lovefield#177]
I would like to use lovefield for an ionic 2 app that will be deployed to iOS and android.
The database size might be large (larger than the 50mb limit).

It would be much better if SQLite can be used as a data store in mobile apps (ionic/cordova). Do you plan to add that?

On the other hand, I know that if Cordova SQLite Plugin 2 (https://github.com/nolanlawson/cordova-plugin-sqlite-2) was installed, PouchDB used SQLite instead of WebSQL out of the box without changes. Does that apply with lovefield?

Thanks

**Comment by arthurhsu** [comment]
I'm not familiar with Cordova, but based on what you have described, you can try the following:

1. Install Cordova SQLite Plugin 2
2. In your code, before loading Lovefield, do this:

window.openDatabase = sqlitePlugin.openDatabase;

3. Load Lovefield, open database using WebSQL

schemaBuilder.connect({storeType: lf.schema.DataStoreType.WEB_SQL}).then(function(db) {
  // Try out Lovefield function here
});

Again, the authors of Lovefield are not omniscient nor omnipotent to know all the answers, so please let us know if this theory worked or not.

**Comment by hatemhosny** [comment]
Thank you for the response.
I'll let you know if it works.
Thanks

**Comment by bianchimro** [comment]
This works for me.

**Comment by hatemhosny** [comment]
I haven't had time to experiment yet.
Thanks for the feedback.

**Comment by arthurhsu** [comment]
Will just close since there's feedback about the proposal works. Feel free to re-open it if the proposal does not work.

**Comment by jacobg** [comment]
Lovefield docs say WebSql support will be removed in near future, but support for it is needed in order to use cordova sqlite to get around db quota limits. Can you clarify please the roadmap for WebSql in this project? Thanks very much.

**Comment by philesc** [comment]
Doesn't works for me on chrome 80.0.3987.149
I got this error : `Sorry first openDatabase argument must be an object`
Any ideas ?
