### ISSUE TITLE
Angular 2 TS suport

### ISSUE THREAD

**Issue by LucasReSilva** [google/lovefield#178]
I can't use angular-cli, angular 2 and lovefield, I got an error importing lovefield "lovefield is not a module". How can I use lovefield with angular 2 typescript?

**Comment by freshp86** [comment]
Does the demo at https://github.com/google/lovefield/tree/master/demos/todo_typescript work for you?

**Comment by LucasReSilva** [comment]
No, the demo not worked to me. It isn't working with ancular-cli generated project( angular2 + Typescript).

**Comment by freshp86** [comment]
Unfortunately the Lovefield team is not familiar with Angular2 (also see this [FAQ](https://github.com/google/lovefield/blob/master/docs/FAQ.md#can-lovefield-be-used-with-angularbootstrapcordovad3-)). I suggest to include a minimal repro example that we can easily examine, as well as asking on the public forum in case some other Lovefield user has already faced this issue.

**Comment by mattblang** [comment]
@LucasReSilva After having run `npm install lovefield` and `npm install @types/lovefield`, are you able to import using `import * as lf from 'lovefield';`? [Here is a side project](https://github.com/mattblang/b4a) that I am working on that was generated with the Angular 2 CLI and uses Lovefield.

**Comment by LucasReSilva** [comment]
Thx @mattblang I did this before, but now I know WHERE to put the the `import * as lf from 'lovefield';`

**Comment by freshp86** [comment]
@LucasReSilva is this resolved now?

**Comment by LucasReSilva** [comment]
Yes, thx @freshp86 and @mattblang
