### ISSUE TITLE
How could I delete table when DataStoreType is MEMEORY

### ISSUE THREAD

**Issue by Brooooooklyn** [google/lovefield#181]
```ts
const schemaBuilder = lf.schema.create('Team', 1)

schemaBuilder.createTable('Test1')
  .addColumn('_id', lf.Type.STRING)
  .addColumn('name', lf.Type.STRING)
  .addPrimaryKey(['_id'])

schemaBuilder.createTable('Test2')
  .addColumn('_id', lf.Type.STRING)
  .addColumn('name', lf.Type.STRING)
  .addPrimaryKey(['_id'])


schemaBuilder.connect(<any>{
  enableInspector: true,
  storeType: lf.schema.DataStoreType.MEMORY,
  onUpgrade: (rawDb: lf.raw.BackStore) => {
    console.log(rawDb)
    return Promise.resolve()
  }
})
```

I noticed that console in onUpgrade callback only be called when `storeType` is `INDEXED_DB`.
So I wonder how could I drop A table when `storeType` is `MEMEORY`.

**Comment by arthurhsu** [comment]
Memory DB is volatile. When you connect to it there's nothing existing, therefore there will be nothing to upgrade from.

**Comment by Brooooooklyn** [comment]
So, could I delete table when `storeType` is `MEMORY`?

**Comment by arthurhsu** [comment]
db.delete().from(table).exec() will delete all records in a table.

**Comment by freshp86** [comment]
> db.delete().from(table).exec() will delete all records in a table.

This is useful if you want to empty an existing table while the application is running.

Otherwise, just delete the table from your schema, and next time you start your application, there will be no such table.

**Comment by Brooooooklyn** [comment]
Actually I'm running test code in `node env`(which means I can only choose `lf.schema.DataStoreType.MEMORY` as storeType) . And I want flush my database after every test suit. So I'm trying to find a way to drop every table that my application has created.

**Comment by arthurhsu** [comment]
Calling db.close() in your tear down function should do it.
