### ISSUE TITLE
Problem with search condition

### ISSUE THREAD

**Issue by Brooooooklyn** [google/lovefield#183]
Assume I have a Table like:
```ts
TaskTable:
{
  _id: PrimaryKey,
  name: string,
  involveMembers: Array<string> // memberId
}
```
How could I select all tasks from TaskTable which involveMembers include the given `memberId`?

I guess maybe I want a operator like :

```
TaskTable.involveMembers.include('fakememberId')
```

**Comment by freshp86** [comment]
From the [spec](https://github.com/google/lovefield/blob/master/docs/spec/01_schema.md#131-columns), columns of type lf.Type.OBJECT are not searchable, except for `isNull()`,  `isNotNull()`. If you need to search, structure your schema in a relational way (one table refers to another). Then you can join tables.
