### ISSUE TITLE
Possibility to run raw sql queries

### ISSUE THREAD

**Issue by pleerock** [google/lovefield#184]
Why lovefield don't support running raw sql queries? I want to integrate lovefield into my [orm](https://github.com/typeorm/typeorm) to make it possible to use indexeddb (currently it supports only websql in beta). But to integrate lovefield to my ORM I need ability run sql queries instead of using embedded api methods.

**Comment by arthurhsu** [comment]
Lovefield will never support parsing raw SQL statements because it is not designed to do so. It is possible to translate SQL into Lovefield APIs and we know some people already did that.

**Comment by freshp86** [comment]
Lovefield's API uses on purpose the builder pattern for describing queries, as in the following example
```
db.select(a.id, a.name).from(a).where(a.id.eq('foo')).exec();
```

The builder pattern has many advantages over parsing free text to produce a query and has been a very deliberate decision.  Including a SQL parser inside Lovefield is not desired, so per design Lovefield does not directly accept SQL queries. Having said that (and as @arthurhsu mentioned above), it is possible to write your own SQL to Lovefield translator.
