### ISSUE TITLE
Running in Pure Javascript Enviornment

### ISSUE THREAD

**Issue by veenedu** [google/lovefield#186]
Hi, 

I am able to sucessfully run lovefield in browser.
When I tried to run lovefield in pure Javascript Environment with in-memory store type, with  `lf.schema.DataStoreType.MEMORY`

single line of code, written below,  generated error.
`var lf = require('lovefield');`

Error::

`node_modules/lovefield/dist/lovefield.min.js:1
(function (exports, require, module, __filename, __dirname) { if(!self.window){window=self;}
                                                                  ^
ReferenceError: self is not defined`

**Comment by veenedu** [comment]
Did some tweaking in `lovefield/dist/lovefield.js`

added this at the beginning of file

`
var window = {
  navigator:{}
}
var self = {};
`

Added this after line 3
```
goog.global = this;   //this is line 3 
goog.global.setTimeout = setTimeout;  //I added this
```

Now it works fine on Node environment with `DataStoreType.MEMORY`. 

Can anyone check the source file and update them, making  sure that this doesn't break anything, and generate the output files that fixes the issue.

**Comment by freshp86** [comment]
There is already a script for running Lovefield in Node, see https://github.com/google/lovefield/blob/master/tools/node_bootstrap.js.

**Comment by arthurhsu** [comment]
Close due to lack of activity.
