### ISSUE TITLE
Syntax error: (550) where() clause includes an invalid predicate

### ISSUE THREAD

**Issue by desvandev** [google/lovefield#192]
Hello!
I'm trying to perform a simple 'where' but I'm getting error 550.
```javascript
let t = this.t[table]; //my schema
return this.db.select(t.id).from(t).where(t.uuid.eq(uuid)).exec();
```

The following works just fine:
```javascript
return this.db.select(t.id).from(t).exec();
```

**Comment by freshp86** [comment]
A call to`getTable()` is required to get the table schema. It is not clear to me how the first statement you posted works. Can you post the entire schema?

**Comment by freshp86** [comment]
Also what is the `lf.Type` of `uuid`? This is important to understand why this error is thrown.

**Comment by desvandev** [comment]
Yeah, I didn't post the entire connection because is a little intricate. But basically "this.t" is:
```javascript
this.t[i] = this.db.getSchema().table(i);
```
However, the connection is ok, that's why a select without ``where`` works ok.

``uuid`` is ``lf.type.STRING``

**Comment by freshp86** [comment]
Can you run debug lovefield and break on every error? This should give you a breakpoint inside https://github.com/google/lovefield/blob/master/lib/eval.js, which would tell us exactly why you are getting this error.

**Comment by desvandev** [comment]
```javascript
lf.eval.Registry.prototype.getEvaluator = function(columnType, evaluatorType) {
  var evaluationMap = this.evalMaps_.get(columnType) || null;
  if (goog.isNull(evaluationMap)) {
    throw new lf.Exception(550); <----------- right here
  }
  var evaluatorFn = evaluationMap.get(evaluatorType) || null;
  if (goog.isNull(evaluatorFn)) {
    throw new lf.Exception(550);
  }
  return evaluatorFn;
};
```

**Comment by freshp86** [comment]
What is the value of `columnType` at that point (is it equal to lf.Type.STRING)? From the source code (where comments are not stripped), 'Could not find evaluation map for the given column type.'

You expect it to be a string, but something seems it's going wrong.

**Comment by desvandev** [comment]
![image](https://cloud.githubusercontent.com/assets/8462871/21941089/e28784b8-d9a5-11e6-94f0-d7adec367db5.png)

Hmm, type_ undefined.

This is where I build my schema:
```javascript
_buildSchema() {
        var schemaBuilder = lf.schema.create(this.db_name, this.db_version);
        var ts = this.db_schema;

        for(let t in ts)
        {
            this.t[t] = null;
            var sb = schemaBuilder.createTable(t);
            var uni = 'uuid';
            var nullables = [];
            for(let c in ts[t]){
                sb.addColumn(c, lf.type[ts[t][c]]);
                if(c!='id')
                    nullables.push(c);
            }
            sb.addColumn(uni, lf.type.STRING); //here I set "uuid" column
            sb.addNullable(nullables);
        }
        return schemaBuilder;
    }
```

**Comment by desvandev** [comment]
I'm a retard, I had a typo in "lf.**t**ype", now I'm getting an error at:
```
goog.asserts.DEFAULT_ERROR_HANDLER	@	lovefield.js:1113
goog.asserts.doAssertFailure_	@	lovefield.js:1124
goog.asserts.assertFunction	@	lovefield.js:1145
goog.Promise.then	@	lovefield.js:2683
```

**Comment by freshp86** [comment]
Glad you figured out the problem. Let's close this bug and move the discussion to the forum. Post a screenshot of the error. The stack is pretty much useless.
