### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by AnixPasBesoin** [google/lovefield#194]
The [link to the demo]( https://www.youtube.com/watch?v=wRiI4p5Uk4E) provided in the [readme.md](https://github.com/google/lovefield) is dead.

> This video is no longer available because the YouTube account associated with this video has been terminated.

**Comment by freshp86** [comment]
Thanks for reporting. It seems that the video has been reuploaded on a different account at https://www.youtube.com/watch?v=pwCzMFoheGw. Will update the README soon.

**Comment by freshp86** [comment]
Issue has been fixed.
