### ISSUE TITLE
Value with different type  can't be unique

### ISSUE THREAD

**Issue by leopard7777777** [google/lovefield#198]
for example:
the type of field ID is  lf.Type.INTEGER with PrimaryKey
{'ID':'111'} and {'ID':111} are regarded as different rows, it can be all inserted into db.
there are two rows.
{'ID':'111'}, {'ID':111}
In fact, the lovefield needs to convert '111' to 111 automatically.

Then i select this table or refresh page.
raise 505 Exception, pk***Index error. so the db is crashed

i think the lovefield check unique by Set.has, the function will distinguish different types of value.
But when init db, check without distinguishing.

Or lovefield can convert type of value to the specified type of field

**Comment by freshp86** [comment]
Lovefield does not perform type checking on the values inserted in the DB for performance reasons. Inserting a string value of '111' where Lovefield expects a numerical value of 111 will cause unexpected behavior. For example if you perform a query with a numerical predicate, it will start returning unexpected results (any indices will be basically corrupted).

In other words, not respecting the schema types is when inserting data in the DB, will cause problems, and Lovefield does not perform implicit conversions on purpose.

**Comment by arthurhsu** [comment]
Work as intended.
