### ISSUE TITLE
BackStore plugin interface

### ISSUE THREAD

**Issue by tracker1** [google/lovefield#201]
It would be nice to see a clear documented interface in order to provide a different BackStore...  One in particular that comes to mind would be the ability to use a [LevelUp](https://github.com/Level/levelup) provider, which would then allow for [any adapter that provides a LevelDown interface for storage](https://github.com/level/levelup/wiki/Modules#storage).

This would make an interesting use case for Node.js and other remote providers beyond Firebase.

**Comment by arthurhsu** [comment]
https://github.com/google/lovefield/blob/master/lib/back_store.js already contains the interface documentation. https://github.com/google/lovefield/tree/master/lib/backstore has many different examples for forking and implementing such adapter.

We do not and will not support "plugin". Backstore is a tightly integrated component that has intimate knowledge about non-public APIs (e.g. row id, table diff) and it makes little sense to expose that.
