### ISSUE TITLE
add dynamic predicate

### ISSUE THREAD

**Issue by nadavten** [google/lovefield#202]
example:
`let predicate = lf.op.and(table.col1.eq(true));

predicate = predicate.and(table.col2.gt(2));`

**Comment by freshp86** [comment]
I can't understand from the snippet above what is the feature you are requesting. Can you elaborate a bit?

**Comment by nadavten** [comment]
forget the snippet. a feature of dynamic predicate is needed

**Comment by freshp86** [comment]
What's a dynamic predicate?

**Comment by freshp86** [comment]
I am closing this due lack of feedback from the reporter.

**Comment by valioDOTch** [comment]
@nadavten Did you want to declare part of a query without executing it at the time of declaration, but when needed?

If that's the case, why not do this yourself via a helper function like so?

function declarePredicate(predicateCodeAsString){
    var fn = new Function("", "return "+predicateCodeAsString+";");
     fn.extend = function extendPredicate(newPredicateCodeAsString){
           return declarePredicate(predicateCodeAsString + "." + newPredicateCodeAsString);
     };
     return fn;
}


var predicate = declarePredicate("lf.op.and(table.col1.eq(true))");
predicate = predicate.extend("and(table.col2.gt(2))");
predicate().exec();
