### ISSUE TITLE
The video no longer available.

### ISSUE THREAD

**Issue by hellonearthis** [google/lovefield#203]
On the https://google.github.io/lovefield/  page is a 
"LOVEFIELD at JS.LA
Overview by Demetrios Papadopoulos
[WATCH NOW](https://www.youtube.com/watch?v=wRiI4p5Uk4E)"
But I get => **This video is no longer available because the YouTube account associated with this video has been closed.**
:(

**Comment by freshp86** [comment]
Thanks for the report. The URL seems to have changed. I'll update the README page. In the meantime you can find the video at https://www.youtube.com/watch?v=pwCzMFoheGw.
