### ISSUE TITLE
IndexedDB 2.0 Support

### ISSUE THREAD

**Issue by rektide** [google/lovefield#205]
I'm looking forward to IndexedDB 2.0's spread. Would be good to see Lovefield support.

Some links:
* [What's New in IndexedDB 2.0](https://hacks.mozilla.org/2016/10/whats-new-in-indexeddb-2-0/)
* [Caniuse PR for IDB 2.0](https://github.com/Fyrd/caniuse/issues/3193)

**Comment by arthurhsu** [comment]
We are already using it for a while: https://github.com/google/lovefield/blob/master/lib/backstore/object_store.js#L115

We are actually the promoter for this getAll() API in Chrome.
