### ISSUE TITLE
'WebSQL is not supported by plattform' although using memory

### ISSUE THREAD

**Issue by belafarinrod91** [google/lovefield#210]
Hi, 

when trying to connect to my database schema with the memory datastore parameter I get the following error: 

> Not supported: (353) WebSQL is not supported by platform.

Here is my (demo) code: 
```
import * as lovefield from 'lovefield';

console.log('DatabaseWebWorker Initialized');

const schemaBuilder = lovefield.schema.create("foo", 1);
schemaBuilder.setPragma({ enableBundledMode: true });
schemaBuilder.createTable("Item").addColumn("id", lovefield.Type.INTEGER); // <- If I comment out this line, the browser doesn't crash.


schemaBuilder.connect(null, lovefield.schema.DataStoreType.MEMORY, null).then(function(db) {
  console.log("Success!");
});
```

The documentation says (https://github.com/google/lovefield/blob/master/docs/spec/03_life_of_db.md): 

> If neither IndexedDB nor WebSQL is supported, use lf.schema.DataStoreType.MEMORY.

So I would expect that it should work even without supporting WebSQL ?

Thanks in advance !

**Comment by freshp86** [comment]
connect() accepts a single object parameter, not three parameters. See example at https://github.com/google/lovefield/blob/8f4f5faac5e6b827f8892e0c77a47fc843aad265/tests/base/close_test.js#L52 on how to properly use connect() with MEMORY.

**Comment by freshp86** [comment]
Posting one more example from the demos/ folder, https://github.com/google/lovefield/blob/741cef2e35ccdaa0b27b03edfed883e7e78c0f18/demos/todo_typescript/todo.ts#L34-L36.

**Comment by belafarinrod91** [comment]
@freshp86 thanks a lot. I already assumed that it's pretty obvious. But that is that obvious - wow. A little bit embarrassing.  Thanks, thanks, thanks !
