### ISSUE TITLE
decoupling from "web apps"

### ISSUE THREAD

**Issue by vbresults** [google/lovefield#211]
Lovefield is a fascinating project, thank you so much for developing it! (:

What do you think about decoupling lovefield from the concept of a web app and separating the API from DB, so we can use it in any JS project with any data store adapter (starting with indexeddb)?

The community could develop MySQL and SQLite adapters for example.  It expands use cases for lovefield significantly, and provide cross-runtime DB access (i.e. Browser, React Native, Node).

My apologies if I've misinterpreted or misunderstood something about how lovefield currently works

**Comment by arthurhsu** [comment]
What makes you think Lovefield is coupled with browser? It is not.
We have examples to use it in Node.js with memory-based backend.
https://github.com/google/lovefield/blob/master/tools/node_bootstrap.js

**Comment by freshp86** [comment]
There has been related discussion at https://groups.google.com/forum/#!searchin/lovefield-users/node%7Csort:relevance/lovefield-users/PdR7MoE-l9A/4G70lNKbAQAJ. Feel free to ask more questions there.
