### ISSUE TITLE
TransactionStats not published to Types

### ISSUE THREAD

**Issue by pamtbaau** [google/lovefield#212]
I was searching for a way to detect the number of rows deleted/inserted and found in the code the definition of TransactionStats(). Unfortunately this definition is not published to Types when installing Lovefield from npm.

Is this an omission or intended?

**Comment by arthurhsu** [comment]
lf.Transaction.prototype.stats returns that. It only reflects stats for explicit transaction that it belongs to.

I don't think Types is the right place to publish it.

**Comment by pamtbaau** [comment]
I'm using vscode with Typescript. When I use an explicit transaction like:
```const articleTbl = Model.db.getSchema().table('Article');
const txn = Model.db.createTransaction();

const deleteStmt = Model.db.delete().from(articleTbl).where(articleTbl['id'].eq(this.id));

txn.exec([deleteStmt]).then(() => {
    const count = txn.stats().deletedRowCount();
});
```
I would expect vscode to show me the stats() method on txn. It doesn't however because the definition of TransactionStats() is not defined in the Types file.
I therefore added the definitions to index.d.ts to allow vscode to show me intellisence on the transaction.

**Comment by freshp86** [comment]
I don't fully understand the problem yet. Are the type definitions at https://github.com/google/lovefield/blob/4d5bb97f0a4aba9ddf9e2e2b23094a63561f54b9/dist/lovefield.d.ts#L69-L84 not correct?

**Comment by pamtbaau** [comment]
Sorry for the confusion...
Yes, the type definitions you are refering to are fine. However when running `npm install @types/lovefield` the definition for stats() is missing on Transaction and TranactionStats is missing.

```
  export interface Transaction {
    attach(query: query.Builder): Promise<Array<Object>>
    begin(scope: Array<schema.Table>): Promise<void>
    commit(): Promise<void>
    exec(queries: Array<query.Builder>): Promise<Array<Array<Object>>>
    rollback(): Promise<void>
  }
```
And also look at DefinitelyTyped: [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/lovefield/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/lovefield/index.d.ts)

**Comment by freshp86** [comment]
Ok. I think understand now. The definitions distributed along with Lovefield (`npm install lovefield`) and the ones at DefinitelyTyped have drifted. In theory those should match each other, but that requires some work, and nobody has found the time to do it.

Another approach would be to modify your setup to use the definitions distributed with Lovefield instead of @types/lovefield.

**Comment by pamtbaau** [comment]
Yes, the ones installed via `npm install lovefield` in `node_modules/lovefield/dist/lovefield.d.ts` are fine. The ones distrubuted via `npm install @types/lovefield` are incomplete.

Because I'm used to installing @types I couldn't find stats() via intellisense.
It's easily solvable once you know... , Just wanted to let you know to prevent others having the same issues as I had.
