### ISSUE TITLE
Can't seem to build custom SPAC library with closure

### ISSUE THREAD

**Issue by mzealey** [google/lovefield#217]
Hi there, looking for a little help with building SPAC/Closure version of the library...

I run the spac compiler like

```
nodejs spac/lovefield-spac --schema schema.yml --namespace songs --outputdir songs
```

which generates a file that looks fine. Then I run

```
java -jar node_modules/google-closure-compiler/compiler.jar \
  --dependency_mode=STRICT --compilation_level ADVANCED \
  --js node_modules/google-closure-library/ \
  --js lib \
  --js songs/songs_gen.js \
  --entry_point=songs --entry_point 'songs.row.Song_source_info' \
  --js_output_file foo.js
```

But this only produces a ~10k file which just seems to contain boilerplate ?! `--compilation_level SIMPLE` seems to produce more code but I thought that the point about SPAC was to produce a fully optimized binary for the database?

**Comment by freshp86** [comment]
The idea of SPAC is to get fully typed, auto-generated database related code. Then you use Closure compiler to bundle your own code that uses Lovefield along with the Lovefield library itself and the auto-generated code, to produce a single JS binary. Does that match your expectation?

> But this only produces a ~10k file which just seems to contain boilerplate ?

Isn't it generating a file that contains everything (not just boilerplate)? Also (maybe helpful), see instructions from another user in the discussion board [here](https://groups.google.com/d/msg/lovefield-users/jxIlb7jtiak/FHjJeMHtAgAJ).

**Comment by mzealey** [comment]
My app currently has a few different classes to handle database under different environments (eg websql, fallback to ajax queries). I am not compiling my app currently with closure. So I was wanting to make a bundle of this new database via lovefield spec that I could compile and load into the app. I will try creating the interface and see if I can compile that with it.

**Comment by freshp86** [comment]
If you are not otherwise already using Closure compiler, then I am not sure if using SPAC is the best approach. It sounds like your use case would benefit more by using the non-SPAC way of using Lovefield (dynamic schema declaration), as in the [quick start](https://github.com/google/lovefield/blob/master/demos/todo/README.md) example.

**Comment by mzealey** [comment]
Thanks for the pointer. I managed to get it compiling now - created the interface in closure and then exported the key parts of it to the app. However when using closure advanced optimizations, it looks like the indexedDB storage keys are being mangled (not sure if this is correct or not) but this means that the values of any keys which have names more than 4 characters are getting set to undefined... This is happening on all tables, but below is an example on a smaller table to illustrate the point:

Looking in chrome indexedDB debugger I see eg the following entry:
```
id: 33
value: {id: "20", name: "blah blah", a: undefined}
```

The creation routine in my code (which seems to be correctly escaped to survive mangling) is:

```
        let rows = to_import['song_source_info'].map( source => song_source_info_table.createRow({
            'id': source['id'],
            'name': source['name'],
            'abbreviation': source['abbreviation'],
        }));
        db.insert().into(song_source_info_table).values(rows).exec();
```

dumping `rows` to the console shows the key names and values are set correctly. Is there some flag I should be passing to closure to avoid mangling the object store key names or is this expected?

Spac definition for this table is:

```
    song_source_info:
        column:
            id: number
            name: string
            abbreviation: string 
        constraint:
            primaryKey:
                - column: id
            nullable:
                - abbreviation
        pragma:
            persistentIndex: true
```

**Comment by arthurhsu** [comment]
The SPAC generated file will properly export row data type, and you need to "cast" your object to the row data type. Please move to our user forum for usage questions like this.
