### ISSUE TITLE
Import data into a schema with datetime fields

### ISSUE THREAD

**Issue by djcouto** [google/lovefield#219]
I've found what I think it's a bug. I have a schema with a **Clients** table just like this
![clients](https://user-images.githubusercontent.com/17494742/31542036-65940bcc-b008-11e7-96ac-ccae5088e13d.png)
and using the method ![import()](https://github.com/google/lovefield/blob/8f4f5faac5e6b827f8892e0c77a47fc843aad265/docs/spec/03_life_of_db.md#37-importexport), I'm trying to populate it with the following json file:
```JSON
{
    "name": "simpledb",
    "version": 1,
    "tables": {
        "Clients": [
            {
                "id": 1,
                "first_name": "Linus",
                "last_name": "Stanton",
                "email": "diam.Pellentesque.habitant@eu.net",
                "address": "Ap #336-8434 Sed Road",
                "birth_date": "1998-05-25 12:59:58"
            }
        ]
    }
}

```
What's happening is that when I do this it throws this error:
```
Uncaught TypeError: value.getTime is not a function
    at rowClass.<anonymous> (lovefield.js:12324)
    at Array.forEach (<anonymous>)
    at rowClass.toDbPayload (lovefield.js:12322)
    at rowClass.lf.Row.serialize (lovefield.js:3938)
    at lf.backstore.ObjectStore.<anonymous> (lovefield.js:6532)
    at lf.backstore.ObjectStore.<anonymous> (lovefield.js:6517)
    at new goog.Promise (lovefield.js:2575)
    at lf.backstore.ObjectStore.performWriteOp_ (lovefield.js:6514)
    at lf.backstore.ObjectStore.<anonymous> (lovefield.js:6531)
    at Array.map (<anonymous>)
```
I've managed a way to work around this issue by changing the line https://github.com/google/lovefield/blob/3e1603ac59de3cca5e6caf5beafc8acf51d79540/lib/schema/table_builder.js#L670 as it follows:
```JAVASCRIPT
-         obj[key] = goog.isDefAndNotNull(value) ? value.getTime() : null;
+         obj[key] = goog.isDefAndNotNull(value) ? new Date(value) : null;
```
Is this happening because of a bug or it's just because of my lack of knowledge as a beginner/enthusiastic?

**Comment by freshp86** [comment]
See an example at https://jsfiddle.net/psLgqo7k/2/. import() is currently designed to work with the output of export(). Once you `JSON.stringify()` the output of export() then the Date object is converted to a string, and therefore you can't directly re-import it back to Lovefield without undoing that conversion manually.

@arthurhsu: Sholud we be smarter in import() to detect Date strings fields and try to convert them to Date() instances?

**Comment by arthurhsu** [comment]
Nope. I think I'm quite clear that import() takes only results from export().
