### ISSUE TITLE
Pull requests appear to be ignored

### ISSUE THREAD

**Issue by valioDOTch** [google/lovefield#220]
There are 5 open pull requests since February 2017 in this project that have passed all tests and are (at least partially) also covered by the Google CLA. 

So far it appears that only the contributors and some bots commented on those requests.

Is the project team not accepting pull requests for some reason currently?
Is it just, that there are no updates?

**Comment by arthurhsu** [comment]
We are not keen on merging minor doc pull requests. It's time consuming merging external pull requests into our internal repositories, therefore we prefer merging code changes instead of doc nits.

**Comment by valioDOTch** [comment]
Thank you for the elaboration @arthurhsu 
I personally consider this an unfortunate situation, but get your POV.
