### ISSUE TITLE
Future alignment with RDB specification?

### ISSUE THREAD

**Issue by js-choi** [google/lovefield#229]
As @arthurhsu said in 2016-02, Lovefield functionally acts as a polyfill of the proposal for the web RDB specification—[or, at least, “90% of it”][90%]. There are several differences between the APIs of Lovefield and RDB’s current draft, as documented in [“rdb: Design Decisions”][] and [“rdb-polyfill: README”][]. Some of these changes, of course, were made because many IndexedDB performance constraints may be ameliorated by natively provided SQL-type query engines.

However, other changes seem to be due to non-performance issues such as developer ergonomics. For example, “the new syntax [for defining tables, indices and constraints] is less verbose and easier to call,” and “observers are greatly simplified because the original observer design in Lovefield provides detailed information than needed in most cases.”

Are there plans to align Lovefield’s API further with RDB’s in a new major version, once RDB has been further standardized, to the extent that would still be performant with an IndexedDB implementation?

[90%]: //github.com/arthurhsu/rdb/issues/2#issuecomment-178057172
[“RDB: Design Decisions”]: //github.com/arthurhsu/rdb/blob/6bf3cdd6bc2ed4716531cae6da7c1697ab6041bf/DESIGN.md
[“rdb-polyfill: README”]: //github.com/arthurhsu/rdb-polyfill/blob/ddc920b1dc2cc81df94311cf0187f071887da419/README.md

**Comment by arthurhsu** [comment]
Currently there is no plan to align the API since I did not secure support from within Chrome for RDB spec. Also Lovefield API changes are very unlikely since we have a very large deployment base and the cost of changing that does not justify in foreseeable future.
