### ISSUE TITLE
Lovefield Roadmap

### ISSUE THREAD

**Issue by sebastianmacias** [google/lovefield#233]
I'm impressed by lovefield's features and its performance and I would like to consider it for projects that require offline databases. Would it be safe to use lovefield in new projects? are there plans to maintain the project in the long term?

**Comment by arthurhsu** [comment]
It's in maintenance mode, which means that we'll do bug fixes and performance tuning for G-Mail internally in Google but will be unlikely to add new features. You are more than welcome to use this library.

**Comment by sebastianmacias** [comment]
Thanks for the info @arthurhsu. Do you know if lovefield will still be used in the new version of Gmail coming up?

**Comment by arthurhsu** [comment]
I did not work on G-Mail so I can't comment on their road map. The only thing I know is that I need to support G-Mail in foreseeable future.
