### ISSUE TITLE
Get current connection?

### ISSUE THREAD

**Issue by Waro1234** [google/lovefield#234]
Hello,

I am trying to make a little program that uses electron (only single instance). I am trying to reuse my connection to a database across several files but I have no idea how to do it.

Example:

In one file i create the tables if they dont exist.
Then in another file i try to add data to that table i created earlier.

How do i reuse the connection so i can achieve this?

Greetings

**Comment by freshp86** [comment]
> I am trying to reuse my connection to a database across several files

The issue you are describing does not sound specific to Lovefield. IIUC, you need to create a singleton instance of a lovefield DB, such that you can use that instance across different files of your app.

There are plenty of examples online on how to do this. Providing a trivial example below (although there are many ways to do it).

```
// file1.js
window.foo = new MySingletonInstance();

// file2.js
console.log('Hey I am using a singleton instance: ' + window.foo);

// index.html
<script src='file1.js'></script>
<script src='file2.js'></script>
```

**Comment by Waro1234** [comment]
Thats a pretty good example, but i figured out that i dont need to reuse that connection the way i thought id had to,

The way i am doing it now is that i create a new Promise, a bit like this
`let p =new Promise(function (resolve,reject) {
        return disDb.insertOrReplace().into(galleryTable).values([galleryRow]).exec();
    });
    p.then(function () {
        return disDb.insertOrReplace().into(filesTable).values(list).exec();
    });`

**Comment by freshp86** [comment]
Closing this bug since there is nothing to fix on the Lovefield side. Feel free to use our forum for general Lovefield usage questions, https://groups.google.com/forum/#!forum/lovefield-users.
