### ISSUE TITLE
How do i make a union query?

### ISSUE THREAD

**Issue by vzaffalon** [google/lovefield#236]
Is there any support for this or do i have to just concat the result of two querys?

**Comment by freshp86** [comment]
Please use the forum for generic usage questions, that are not bugs/feature-requests.

Regarding union, I assume you are looking something equivalent to SQL's OR operator. If so, see [lf.op.or()](https://github.com/google/lovefield/blob/master/docs/spec/04_query.md#413-search-conditions) Lovefield operator.
