### ISSUE TITLE
Publish NPM Module

### ISSUE THREAD

**Issue by mbleigh** [google/lovefield#24]
If you'd like to see wider adoption of this, I'd very strongly recommend you figure out a way to make the bundle compiler as simple as:

```
npm install -g lovefield
lovefield my_schema.yml
```

Having to manually install dependencies and the location of the closure compiler just isn't how things are done in the wider web world. Additionally, there should be easy hooks for others to build ecosystem plugins for things like Grunt, Gulp, etc.

Not trying to sound grumpy, but I think Lovefield is a really cool project and I'd like to see it get all the adoption it can get! :ghost: :smile_cat:

**Comment by freshp86** [comment]
FYI, Lovefield is now available through NPM, see https://www.npmjs.com/package/lovefield.
