### ISSUE TITLE
Required NOT IN feature

### ISSUE THREAD

**Issue by rkbansal** [google/lovefield#248]
Hey guys can you provide something like
`NOT (verificationStatus IN ["entered-in-error", "refuted"])`
which means take all expect where varificationStatus either entered-in-error or refuted.

It will be very helpful, thanks..

**Comment by freshp86** [comment]
This is already supported. See the test at https://github.com/google/lovefield/blob/6e6cc7cae1421a8da6d5e55ffecb0cdedf6b29a6/tests/pred/not_operator_test.js#L101-L116. Your query would look as follows

```
const excluded = [...];
 db.select().
     from(myTable).
     where(lf.op.not(myTable.verificationStatus.in(excluded))).
     exec();
```
