### ISSUE TITLE
Silly Question: Lovefield and Apps Script

### ISSUE THREAD

**Issue by everythingability** [google/lovefield#258]
Please forgive my ignorance. 

As ORMs go this looks lovely. Would it, "in theory" be possible to use Lovefield in an Apps Script web app (i.e not Node.js per se) to talk to Firebase?  Or is that a complete non-starter?

Thanks

Tom

**Comment by arthurhsu** [comment]
We tried it before and it worked to some degree. However, we no longer actively work on integrating with Firebase and therefore you'll need to try it again with the new APIs shipped by Firebase.

Your mileage may vary depending on how the backend (e.g. Firebase) provides its transaction support.
