### ISSUE TITLE
Cannot insert ArrayBuffer correctly !

### ISSUE THREAD

**Issue by LLLLLLiulei** [google/lovefield#265]
<img width="647" alt="QQ20200806-192010@2x" src="https://user-images.githubusercontent.com/18627197/89527181-811b7b80-d81b-11ea-90f9-67a80c623da7.png">

![QQ20200806-191949](https://user-images.githubusercontent.com/18627197/89527202-8973b680-d81b-11ea-85dc-693d48680dcb.png)

**Comment by arthurhsu** [comment]
This is by design. Lovefield stores ArrayBuffer in hex strings.
