### ISSUE TITLE
Where's the manual?

### ISSUE THREAD

**Issue by coisox** [google/lovefield#275]
Beside sample in todo.html, where's the rest manual? Example I found people are using addNullable(). How do they know such thing exist? Now I'm googling for how to set auto increment primary key but the code I found was from 2015 which cause me error

**Comment by freshp86** [comment]
addNullable() is mentioned in the specification, see https://github.com/google/lovefield/blob/master/docs/spec/01_schema.md#131-columns. IN general you'll find a lot of useful info on how to use Lovefield at https://github.com/google/lovefield/tree/master/docs/spec.
