### ISSUE TITLE
Spurious errors thrown when Lovefield is used with Browserify.

### ISSUE THREAD

**Issue by le0pard** [google/lovefield#33]
Hello. Still continue trying to use library in Chrome App. Now I get another problem, when trying to `connect()` to schema:

![developer tools - chrome-extension cipdlhkjnhaejbgafpfhegddnhfimlhn index html 2015-05-11 23-23-32](https://cloud.githubusercontent.com/assets/98444/7574278/cf90c85a-f834-11e4-99b8-8bc0376a84b5.png)

Errors: "document.open() is not available in packaged apps." and "Uncaught Error: document.write() is not available in packaged apps."

Tools:
 * grunt v0.4.5
 * browserify v10.1.3
 * lovefield v2.0.50

**Comment by freshp86** [comment]
Lovefield library does not call document.write, or document.open anywhere. So I am not really sure of how to debug this. I can see in the stack that lovefield.min.js shows up, but the error might be thrown from elsewhere, and just be caught within some handler in the lovefield.min.js (not sure).

The first step to debug would be to use the lovefield.js (non-minified) debug version, but I know this caused another error in your app, so maybe that needs to be figured out first.

Also, is there a way I can check out your app and reproduce the problem? Having said that, Lovefield is being used  in other Chrome Apps successfully, so the problem might be elsewhere in your setup.

**Comment by le0pard** [comment]
Hello @freshp86 .

For non-minified version still get error: "Uncaught TypeError: Cannot set property 'Error' of undefined"

Line: 4053
Code on this line:

```js
goog.debug.Error = function(opt_msg) {
```

As I understand, `goog.debug` not defined, what is why get error for `goog.debug.Error`.

To reproduce problem, you can try run my project:

```bash
git clone https://github.com/le0pard/cloud-control-client.git
cd cloud-control-client
npm install
bower install
grunt dev
```

And open in chrome `dev` folder as unpacked app. This app is just bootstrap, so it contain some libs, but it just show some views, nothing more. Problem in this file: https://github.com/le0pard/cloud-control-client/blob/master/app/scripts/frontend/utils/databases/IndexedStorageDB.js.es6 Uncomment `connect()` and you will get error.

**Comment by freshp86** [comment]
So I created a small example where lovefield is used in a Chrome App. Please take a look at https://github.com/freshp86/chrome-app-samples/commit/5713ba71027bc8e31ae46e336d322c7e2d020881. I just modified the sample "calculator" app to create a small schema and write something to the DB. It works fine without throwing any errors, which makes me thing that something else is causing the errors in your setup environment.

Thank you

**Comment by freshp86** [comment]
I had to add some files I forgot to commit in my example. Please check out https://github.com/freshp86/chrome-app-samples/tree/master/samples/calculator and try loading it as an "unpacked" chrome app, and see if that works for you.

**Comment by le0pard** [comment]
Hello @freshp86 

Looks like I found, where library call "document.write, or document.open". Here this code: 

```js
goog.async.nextTick.getSetImmediateEmulator_ = function() {
  // Create a private message channel and use it to postMessage empty messages
  // to ourselves.
  var Channel = goog.global['MessageChannel'];
  // If MessageChannel is not available and we are in a browser, implement
  // an iframe based polyfill in browsers that have postMessage and
  // document.addEventListener. The latter excludes IE8 because it has a
  // synchronous postMessage implementation.
  if (typeof Channel === 'undefined' && typeof window !== 'undefined' &&
      window.postMessage && window.addEventListener &&
      // Presto (The old pre-blink Opera engine) has problems with iframes
      // and contentWindow.
      !goog.labs.userAgent.engine.isPresto()) {
    /** @constructor */
    Channel = function() {
      // Make an empty, invisible iframe.
      var iframe = document.createElement(goog.dom.TagName.IFRAME);
      iframe.style.display = 'none';
      iframe.src = '';
      document.documentElement.appendChild(iframe);
      var win = iframe.contentWindow;
      var doc = win.document;
      doc.open();
      doc.write('');
      doc.close();
      // Do not post anything sensitive over this channel, as the workaround for
      // pages with file: origin could allow that information to be modified or
      // intercepted.
      var message = 'callImmediate' + Math.random();
      // The same origin policy rejects attempts to postMessage from file: urls
      // unless the origin is '*'.
      // TODO(b/16335441): Use '*' origin for data: and other similar protocols.
      var origin = win.location.protocol == 'file:' ?
          '*' : win.location.protocol + '//' + win.location.host;
      var onmessage = goog.bind(function(e) {
        // Validate origin and message to make sure that this message was
        // intended for us. If the origin is set to '*' (see above) only the
        // message needs to match since, for example, '*' != 'file://'. Allowing
        // the wildcard is ok, as we are not concerned with security here.
        if ((origin != '*' && e.origin != origin) || e.data != message) {
          return;
        }
        this['port1'].onmessage();
      }, this);
      win.addEventListener('message', onmessage, false);
      this['port1'] = {};
      this['port2'] = {
        postMessage: function() {
          win.postMessage(message, origin);
        }
      };
    };
  }
  if (typeof Channel !== 'undefined' &&
      (!goog.labs.userAgent.browser.isIE())) {
    // Exclude all of IE due to
    // http://codeforhire.com/2013/09/21/setimmediate-and-messagechannel-broken-on-internet-explorer-10/
    // which allows starving postMessage with a busy setTimeout loop.
    // This currently affects IE10 and IE11 which would otherwise be able
    // to use the postMessage based fallbacks.
    var channel = new Channel();
    // Use a fifo linked list to call callbacks in the right order.
    var head = {};
    var tail = head;
    channel['port1'].onmessage = function() {
      if (goog.isDef(head.next)) {
        head = head.next;
        var cb = head.cb;
        head.cb = null;
        cb();
      }
    };
    return function(cb) {
      tail.next = {
        cb: cb
      };
      tail = tail.next;
      channel['port2'].postMessage(0);
    };
  }
  // Implementation for IE6+: Script elements fire an asynchronous
  // onreadystatechange event when inserted into the DOM.
  if (typeof document !== 'undefined' && 'onreadystatechange' in
      document.createElement(goog.dom.TagName.SCRIPT)) {
    return function(cb) {
      var script = document.createElement(goog.dom.TagName.SCRIPT);
      script.onreadystatechange = function() {
        // Clean up and call the callback.
        script.onreadystatechange = null;
        script.parentNode.removeChild(script);
        script = null;
        cb();
        cb = null;
      };
      document.documentElement.appendChild(script);
    };
  }
  // Fall back to setTimeout with 0. In browsers this creates a delay of 5ms
  // or more.
  return function(cb) {
    goog.global.setTimeout(cb, 0);
  };
};

```


exactly this line:

```js
var win = iframe.contentWindow;
var doc = win.document;
doc.open();
doc.write('');
doc.close();
```

So looks like it call `document.open()` and `document.write()`.

**Comment by freshp86** [comment]
I am trying to run your code, but I am getting a different error,
chrome-extension://mfmgebilkgaadaebkhpncpdebcjcbbph/scripts/frontend.js Failed to load resource: net::ERR_FILE_NOT_FOUND

In the meantime did you try https://github.com/freshp86/chrome-app-samples/tree/master/samples/calculator?

**Comment by le0pard** [comment]
> I am trying to run your code, but I am getting a different error,
chrome-extension://mfmgebilkgaadaebkhpncpdebcjcbbph/scripts/frontend.js Failed to load resource: net::ERR_FILE_NOT_FOUND

`grunt dev` not build js files.

> In the meantime did you try https://github.com/freshp86/chrome-app-samples/tree/master/samples/calculator?

Yes, looks like it works. Trying js file from calculator instead of npm package. Maybe this will help.

**Comment by le0pard** [comment]
Hello, @freshp86 .

I found problem. lovefield doesn't support http://browserify.org/. After changes of you example to build by browserify (https://gist.github.com/le0pard/db4700a041eedb98e83c) I get error: "Uncaught TypeError: Cannot set property 'Error' of undefined"

To reproduce go to calculator folder: 

```bash
npm install -g browserify
browserify controller.js > build.js
```

And you get this error :)

**Comment by freshp86** [comment]
That is a good finding. I don't know at this point what would it take for Lovefield to be "require-able" by browserify, given that the problem seems to be caused by Closure Library which Lovefield uses internally. I 'll update this thread, if I find any solutions, but in the meantime I believe you can simply include lovefield.min.js in your HTML doc, and stop requiring it through browserify.

**Comment by le0pard** [comment]
Thanks @freshp86 

> I 'll update this thread, if I find any solutions, but in the meantime I believe you can simply include lovefield.min.js in your HTML doc, and stop requiring it through browserify.

Yes, for development I can just add it in HTML. Only release will need build it inside one JS file :)

**Comment by freshp86** [comment]
FWIW, I did some initial investigation and the problem seems to be that when using browserify, "this" is not Window, and therefore things start to break down within the Closure library. I could not find a fix yet, tried the following,

Change the following line in build.js (line 37909 in my case)
},{}],3:[function(require,module,exports){
to
}.bind(window),{}],3:[function(require,module,exports){
or
}.bind(this),{}],3:[function(require,module,exports){

None of those worked, but the problem is clearly in closure https://github.com/google/closure-library/blob/master/closure/goog/base.js#L42,L48, and https://github.com/google/closure-library/blob/master/closure/goog/base.js#L119.

**Comment by freshp86** [comment]
I should also note that this is easier to debug if you run calculator.html as a webpage and not as a Chrome App, otherwise you can't add a breakpoint in time, (you will be hitting this bug https://code.google.com/p/chromium/issues/detail?id=168085).

**Comment by le0pard** [comment]
We are using something like this to support AMD, Browserify and WebPack systems:

```js
var root = typeof exports !== "undefined" && exports !== null ? exports : this;

// our lib code

// is AMD?
if (typeof define === "function" && define.amd) {
  define([], function() {
    return OurObject;
  });
} else {
  root.OurObject = OurObject;
}
```

**Comment by freshp86** [comment]
FYI, I made some changes to Lovefield's debug binary lovefield.js and I no longer get the error (using your patch from https://gist.github.com/le0pard/db4700a041eedb98e83c). Will be landing this change sometime later today. Perhaps you can give it another try. Will ping this thread once the new lovefield.js is in the repo.

**Comment by le0pard** [comment]
Thanks @freshp86 Will wait for you response about new lovefield.js and try it again in project.

**Comment by freshp86** [comment]
Pushed the updated lovefield.js so feel free to retry (either sync to head, or get 2.0.53 from NPM, or lovefield#master from bower).

BTW I remember that you also had some issues when using the lovefield.min.js, which I think are unrelated to the issue here, but not sure yet.

**Comment by le0pard** [comment]
Hello, @freshp86 Looks like problem in different errors for min and non-min version removed. Now I have the same error for both versions:

![developer tools - chrome-extension cipdlhkjnhaejbgafpfhegddnhfimlhn index html 2015-05-19 00-36-40](https://cloud.githubusercontent.com/assets/98444/7690765/2b9d4fda-fdbf-11e4-93b3-cabfddaf395c.png)

![developer tools - chrome-extension cipdlhkjnhaejbgafpfhegddnhfimlhn index html 2015-05-19 00-37-45](https://cloud.githubusercontent.com/assets/98444/7690791/62c6efa2-fdbf-11e4-8d84-43b7dd8fe4f7.png)

So library really try to do "document.open" and "document.write" in method "goog.async.nextTick.getSetImmediateEmulator_".

Example of code:

```
schemaBuilder = lf.schema.create('cloud-database', 1);
schemaBuilder.createTable('accounts').
      addColumn('id', lf.Type.INTEGER).
      addColumn('type', lf.Type.STRING).
      addColumn('title', lf.Type.STRING).
      addColumn('provider_key', lf.Type.STRING).
      addColumn('provider_secret', lf.Type.STRING).
      addColumn('is_default', lf.Type.BOOLEAN).
      addPrimaryKey(['id']).
      addIndex('idxType', ['type'], false, lf.Order.ASC);
/* connect to database */
schemaBuilder.connect();
```

**Comment by freshp86** [comment]
This one I can't reproduce. I am not sure why your code is calling the goog.async.nextTick.getSetImmediateEmulator_ function. It seems that you might have a global var (maybe from some other dependency?) with the name "setImmediate", see https://github.com/google/closure-library/blob/32365aba43acb36c5d693256ef5d4dbe3bddddfe/closure/goog/async/nexttick.js#L81.

**Comment by le0pard** [comment]
Thanks @freshp86 , will check this tomorrow. Maybe also babel (es6 to es5 convertor) influence (but I set it convert only my libs)

**Comment by freshp86** [comment]
@le0pard: Any news on this?

**Comment by le0pard** [comment]
@freshp86 Sorry, was very busy weeks. I will try debug this issue tomorrow and will write about results here.

**Comment by le0pard** [comment]
Hello, @freshp86 . Sorry for delay. Just installed latest lovefield v2.0.56. Right now it return empty JS object from import:

![developer tools - chrome-extension 3a 2f 2fcipdlhkjnhaejbgafpfhegddnhfimlhn 2findex html 2015-06-04 19-13-23](https://cloud.githubusercontent.com/assets/98444/7988804/f88c60b8-0aed-11e5-829a-72ec8df91589.png)

in ES6:

```js
import lovefield from 'lovefield';
logger.debug('lovefield', lovefield);
```

compiled to ES5:

```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _lovefield = require('lovefield');
var _lovefield2 = _interopRequireDefault(_lovefield);

var _utilsLoggerJsEs6 = require('../../utils/logger.js.es6');

var _utilsLoggerJsEs62 = _interopRequireDefault(_utilsLoggerJsEs6);
_utilsLoggerJsEs62['default'].debug('lovefield', _lovefield2['default']);
```

**Comment by freshp86** [comment]
I think the problem is that lovefield.min.js currently is not designed to be used with browserify. We are not exporting anything (like exports.foo = bar), which is why I think the object is empty.

As far as I know, in order to use Lovefield currently, you need to add a <script> in your page, and then use the global "lf" object, as it is done in our demos, for example see https://github.com/google/lovefield/blob/master/demos/olympia_db/angular/demo.html#L7.

So the action item here, is to see what is needed to make Lovefield browserify-friendly. My guess is that all we need is to add the necessary "exports" statements, but not sure if we need a new binary only for browserify, something like lovefield.browserify.min.js, or if we can keep using a single JS binary.

**Comment by le0pard** [comment]
@freshp86 Ok, `exports = lf;` helped. And I don't have errors. Thanks!

**Comment by freshp86** [comment]
I am re-opening this issue since the problems have come returned after https://github.com/google/lovefield/commit/624e553ed00f68330949ff9cbff356deefd71c3d. I think I have a fix that can make the same JS binary work for both a WebWorker and Browseify.
