### ISSUE TITLE
Optimize join ordering in N-table joins where N > 2.

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#4]
order_by needs to be optimized
3-table join needs to be optimized

**Comment by freshp86** [comment]
FYI, ORDER_BY is optimized (long time now), using the OrderByIndex optimization pass. I will rename this bug to better reflect what is left to do here.

**Comment by freshp86** [comment]
Closing this one, since it is now a duplicate of https://github.com/google/lovefield/issues/41.
