### ISSUE TITLE
Improve row serialize/deserialize performance 

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#40]
Profiler said that row serialize/deserialize is the super-hot code path that needs to be optimized.

**Comment by agershun** [comment]
According my previous tests, JSON.stringify/parse are fastest functions for serialization/deserialization. Unfortunately, they are both very slow.

**Comment by arthurhsu** [comment]
What I meant here is the DB type to row type conversion. IndexedDB does not store some data types (Date, ArrayBuffer on some browsers) so need special conversion. That part of code is super hot for bootstrapping and insert/update/delete.

**Comment by arthurhsu** [comment]
Existing serialization is already the best practice, and we did not find anywhere we are doing excessive clones.
