### ISSUE TITLE
Polymer README.md Step 7 documentation is pointing to the angular demo...

### ISSUE THREAD

**Issue by cherukumilli** [google/lovefield#46]
The README.md file at: https://github.com/google/lovefield/tree/master/demos/olympia_db/polymer needs to be corrected 
from:
Step 7: Navigate to http://localhost:8000/demo-angular.html, and start making queries.
to:
Step 7: Navigate to http://localhost:8000/demo_polymer.html, and start making queries.

**Comment by freshp86** [comment]
Fixed at https://github.com/google/lovefield/commit/ab5945abd6b252a3db591c6858d5cbf76d2cf986.
