### ISSUE TITLE
gulp build failure

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#49]
Building... 34 of 93 tests/harness/min_js/lovefield_min_test.js

tests\harness\min_js\lovefield_min_test.js:109: ERROR - variable lf is undeclared
  var schemaBuilder = lf.schema.create('apicheck', 1);
                      ^

1 error(s), 0 warning(s)

**Comment by freshp86** [comment]
Fixed by https://github.com/google/lovefield/commit/a9f130b78bb68723b38d5a215a55535ad27b2fce.
