### ISSUE TITLE
movieDB demo broken on HEAD

### ISSUE THREAD

**Issue by freshp86** [google/lovefield#54]
The demo is broken by two separate bugs.

1. 
Uncaught ReferenceErrror: goog is not defined
Uncaught ReferenceError: movie is not defined
caused by lines 
https://github.com/google/lovefield/blob/master/demos/moviedb/schema.js#L17-22

2. addForeignKey is called with the wrong parameters at
https://github.com/google/lovefield/blob/master/demos/moviedb/schema.js#L69
causing a different runtime error.

**Comment by arthurhsu** [comment]
fixed 7367b372ed05c1e98c2d45b60caf5cd13229c79e
