### ISSUE TITLE
Not able to add Foreign Key

### ISSUE THREAD

**Issue by vikasprogrammer** [google/lovefield#56]
I am using the following code from the <> example to add a foreign key:

`addForeignKey('fk_ActorId', 'actorId', 'Actor', 'id');`

But I am getting following error :

`Uncaught TypeError: Cannot read property 'split' of undefined : lovefield.js:10844` 

on the following code:

    lf.schema.ForeignKeySpec = function(rawSpec, name) {
      var array = rawSpec.ref.split("."); //ERROR IS ON THIS LINE.
      if (2 != array.length) {
        throw new lf.Exception(540, name);
      }
      this.childColumn = rawSpec.local;
      this.parentTable = array[0];
      this.parentColumn = array[1];
      this.name = name;
      this.action = rawSpec.action;
      this.timing = rawSpec.timing;
    };

Have you changed the way a foreign key is created? I cannot find documentation about it.

**Comment by arthurhsu** [comment]
The addForeignKey API signature had changed. Please see

https://github.com/google/lovefield/blob/master/tests/schema/builder_test.js#L49

for an example of new usage.
