### ISSUE TITLE
Would you push git tag to GitHub, please?

### ISSUE THREAD

**Issue by sanemat** [google/lovefield#61]
I want to read the diff between versions. This is a bit hard without git tag :cry:

**Comment by freshp86** [comment]
Thanks for the suggestion. Adding git tags sounds useful. I 'll try to add git tags retroactively for previously released versions, and make sure we also add them for newer versions from now on. Will update this thread once done.

**Comment by indera** [comment]
First tag available
https://github.com/google/lovefield/releases/tag/v2.0.61

**Comment by arthurhsu** [comment]
We'll just add tags for releases from now on. I don't see a good use of time to tag previous releases.

**Comment by sanemat** [comment]
Thanks!
