### ISSUE TITLE
Inner join not working in Safari

### ISSUE THREAD

**Issue by kenjitayama** [google/lovefield#63]
I'm experiencing strange errors using inner join in Mac Safari.

I've made a live reproduction.
http://bl.ocks.org/kenjitayama/5d4ad3b0a45b7a7af82e

This is a modification of demos/todo/todo.html, adding another table and doing an inner join.

I needed to load an old commit of lovefield.js due to issue #62, otherwise even a single table query would not work.

In Chrome, you can see something like this
```
Get a cup of coffee before Mon Aug 03 2015 14:31:52 GMT+0900 (JST). OK!
```

But in Safari, you get this error.
```
NotFoundError: DOM IDBDatabase Exception 8: An operation failed because the requested database object could not be found.
```

Mac Safari version
8.0.7 (10600.7.12)

**Comment by arthurhsu** [comment]
Safari 8's IndexedDB implementation is very buggy and not usable. See http://www.raymondcamden.com/2014/09/25/IndexedDB-on-iOS-8-Broken-Bad

You'll need to use the WebSQL store instead. Please alter the TODO code as the following diff snippets suggested:

@@ -20,7 +20,7 @@ schemaBuilder.createTable('Item').

 var todoDb;
 var item;
-schemaBuilder.connect().then(function(db) {
+schemaBuilder.connect({storeType: lf.schema.DataStoreType.WEB_SQL}).then(function(db) {
   todoDb = db;
   item = db.getSchema().table('Item');
   var row = item.createRow({

**Comment by kenjitayama** [comment]
Thanks for the quick response!
Switching to WebSQL made it work in Safari.
http://bl.ocks.org/kenjitayama/97c1250ebfbfe037bbf5

**Comment by freshp86** [comment]
It's better to fall back to WebSQL only in Safari, but keep using IDB in other browsers. IDB backend is faster than WebSQL according to our tests, so WebSQL should only be used in Safari. For example
```
var isSafari = .......; // some browser detection code here.
var connectOptions = {
  storeType: isSafari ? lf.schema.DataStoreType.WEB_SQL : lf.schema.DataStoreType.INDEXED_DB
};
schemaBuilder.connect(connectOptions).then(...);
```

**Comment by kenjitayama** [comment]
@freshp86 Thanks for the tip!
