### ISSUE TITLE
Css issue on your web page preventing you seeing the download button

### ISSUE THREAD

**Issue by TusharaFernando** [google/lovefield#67]
![image](https://cloud.githubusercontent.com/assets/6848978/9766947/85297972-5713-11e5-8f53-65b7630c42a6.png)
Chrome latest 1240*820

**Comment by freshp86** [comment]
Thanks for reporting. The problem was that the footer was absolutely positioned, and overlapped with the download button. Fixed by https://github.com/google/lovefield/commit/1d9df83bcb2198b08c80fcd0c3a18c6a34593869.
