### ISSUE TITLE
LoveField with Web worker

### ISSUE THREAD

**Issue by rajivmehtaflex** [google/lovefield#69]
I'm try to use Lovefield library in conjuction with web worker.It's throw following error while using

importScripts("lovefield.js");

Uncaught Error: Uncaught ReferenceError: window is not defined.

Kindly Guide.

**Comment by freshp86** [comment]
Thanks for reporting this. I can reproduce and a fix should be coming soon.

**Comment by rajivmehtaflex** [comment]
Thanks for support.waiting for your fixes

**Comment by freshp86** [comment]
FYI I was able to successfully run within a web worker by adding the following line at the top of lovefield.js.

```
var window = this;
```

Need to test a bit more to ensure that this does not break anything else though, before moving forward with this fix.
