### ISSUE TITLE
Why not store the schema separately ?

### ISSUE THREAD

**Issue by mingodad** [google/lovefield#75]
Hello !
I've been looking at the mvidb and others and noticed that the rows are stored as json objects (repeating key:value on every row), would not be more better to store the schema info (col names, col positions, col types, constraints,...) on a separated "table" (aka data catalog) and store the rows as json arrays (no keys "column names" repeated) the database would be smaller and probably faster.

Cheers !

**Comment by freshp86** [comment]
Regarding storing the schema separately, see https://github.com/google/lovefield/issues/58.

Regarding the potential performance gains by doing so, it would be worth experimenting. One problem I see though, is that there would be a performance penalty of converting the "compact" object payloads, to the format that is expected to be returned to the user. Today, the format we store in the DB, is the same as the one returned to the user, so there is minimal conversion penalty.

**Comment by arthurhsu** [comment]
Dup https://github.com/google/lovefield/issues/64
