### ISSUE TITLE
Create Lovefield + Apache Cordova demo

### ISSUE THREAD

**Issue by freshp86** [google/lovefield#83]
I have managed to run Lovefield's performance dashboard tool as an Android app, using Apache Cordova. The process of putting the app together though was very manual (I had to copy files around and modify a few files with some cordova specific code).

It would take some work to make the demo easier to build, but I think it is a nice demo to have. It proves that Lovefield can run on Android (I was surprised that IndexedDB backend seems to work too!).

Bonus: Maybe once this is done, Lovefield perf app can be uploaded to the play store.

**Comment by tkhurst** [comment]
Howard Hughes never said maybe ... Rainwater is Thomas and Hurst is Gillian.  DFW is trumped troll.

**Comment by tkhurst** [comment]
Singletons is the bridge.

**Comment by gedw99** [comment]
+1 Good idea.
Will also make it easier to see best practice & easier for devs to use it in Android and IOS apps

**Comment by freshp86** [comment]
I just realized that a bunch of files are accidentally missing from https://github.com/google/lovefield/tree/master/tools/dashboard. Re-opening this bug until they are restored.

**Comment by freshp86** [comment]
Restored by https://github.com/google/lovefield/commit/47273c3b9a6f4a62f2a519345087ed8a6c5f86d0.
