### ISSUE TITLE
Update and check compat for Underscore 1.8.3

### ISSUE THREAD

**Issue by robertbaker** [google/lovefield#88]

**Comment by arthurhsu** [comment]
See FAQ https://github.com/google/lovefield/blob/master/docs/FAQ.md#can-lovefield-be-used-with-angularbootstrapcordovad3-

Unless there are repro steps to prove Lovefield does not work with Underscore 1.8.3, I'll close this issue.

**Comment by robertbaker** [comment]
My mistake thought this was causing a downgrade in underscore to 1.7 due to package.json deps, but it doesn't use it.
