### ISSUE TITLE
get database instead of create

### ISSUE THREAD

**Issue by xionglun** [google/lovefield#90]
I  cannot find any document that explain how to get an existing db, all examples like below
```javascript
// SQL equivalent: CREATE DATABASE todo
var schemaBuilder = lf.schema.create('todo', 1);
```

Do I have to create it every time?

**Comment by arthurhsu** [comment]
You are creating schema every time, not the database. Please redirect usage questions to our public forum.

Duplicate of https://github.com/google/lovefield/issues/58
