### ISSUE TITLE
undefined is not an object (evaluating 'c.Af')

### ISSUE THREAD

**Issue by pedrorw** [google/lovefield#93]
Hi guys,

I'm getting this error in safari 8.0.8

I clicked in the error http://127.0.0.1:3000/lib/lovefield/dist/lovefield.min.js:230:230 and I got to this code:

function vi(a) {
    this.bf = this.Af=!1;
    this.bg = O();
    this.od = a
}

basically I got different exceptions but all of them ends at the same piece of code.

any hint about this issue?

**Comment by freshp86** [comment]
Can you post the code you are executing that leads to this error?

**Comment by arthurhsu** [comment]
Please direct usage questions to https://groups.google.com/forum/#!forum/lovefield-users and list where can we find your code. The issues are for contributors to solve real bugs in Lovefield, and propose for new features.
