### ISSUE TITLE
firebase scrum demo not working

### ISSUE THREAD

**Issue by TimWillis** [google/lovefield#95]
After following the readme in the example to install all dependencies I can go to my localhost index.html file and it runs fine, but when I go to index_firebase.html I get the following error: Uncaught TypeError: Cannot read property 'tb' of null

I have set up a firebase test db for the data store and it populates it with this
{
  "scrum" : {
    "@db" : {
      "version" : 1
    },
    "@rev" : {
      "R" : 1
    },
    "@table" : {
      "person" : 0,
      "task" : 1
    }
  }
}

**Comment by arthurhsu** [comment]
Demo is broken by 5421e7a8d25b77ffa57fccb15e1e23651fb93993
Working on a fix now, thanks for reporting.

**Comment by TimWillis** [comment]
OK, Thank you.

**Comment by arthurhsu** [comment]
Fixed 9ff34c5bbc2aa3853bc44721c1decfd1a6a2cff7
