### ISSUE TITLE
Use lovefield application with angular javascript

### ISSUE THREAD

**Issue by euclid1990** [google/lovefield#97]
I have created my application use Lovefield DB to management task.
It use local indexed DB. If the deadline of task is now, it push web browser notification and play sound.

##### Demo: http://euclid1990.github.io/task/#/

**Comment by arthurhsu** [comment]
Not sure what's your point. Issues are for Lovefield bugs. If you want to show off your demo, our public forum will be a better place. https://groups.google.com/forum/#!forum/lovefield-users
