### ISSUE TITLE
firebase 2nd insert transaction ignores primary and does insert.

### ISSUE THREAD

**Issue by TimWillis** [google/lovefield#98]
To see this you can use the example and just change line 55 of index_firebase.html to 
return this.fillData_();//(results[0]['COUNT(*)'] == 0) ? this.fillData_() : Promise.resolve();

Then load the page 2 times. The second load inserts into firebase and creates duplicate records with a different R number. Then the query returns the duplicate data.

**Comment by arthurhsu** [comment]
I assume you're talking about data_mode_firebase.js instead of index_firebase.html. The second run shall throw exceptions due to primary key violation. Need to investigate.

**Comment by TimWillis** [comment]
Yes, that is the file I meant, sorry about that.

**Comment by TimWillis** [comment]
@arthurhsu  Awesome, thank you!
